[tool.poetry]
name = "projetos"
version = "0.1.0"
description = ""
authors = ["Artur Assis Alves <arturassiscomp@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
